name: CI
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
env:
  DOTNET_VERSION: '6.0.100-rc.2'
  
jobs:
  build-and-test:
    name: build-and-test-${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.2.106'
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.100-preview.4.21255.9'
          include-prerelease: true
#       - uses: actions/checkout@v2
#       - name: Setup .NET Core
#         uses: actions/setup-dotnet@v1
#         with:
#           dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore
      
      - name: Test
        run: dotnet test test/MASA.BuildingBlocks.DDD.Domain.Tests/MASA.BuildingBlocks.DDD.Domain.Tests.csproj
