name: CI
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
env:
  DOTNET_VERSION: '6.0.100-rc.2'
  
jobs:
  build-and-test:
    name: build-and-test-${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
#         os: [ubuntu-latest, windows-latest, macOS-latest]
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: install dotnet 
        run: |
          $src = 'https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.ps1'
          $des = 'D:\a\dotnet-install.ps1'
          Invoke-WebRequest -uri $src -OutFile $des
          cd D:\a\
          ls 
          D:\a\dotnet-install.ps1 -Channel  6.0
          dotnet tool install  --global dotnet-ef 
          dotnet test ./myavtive01/test/MASA.BuildingBlocks.DDD.Domain.Tests/MASA.BuildingBlocks.DDD.Domain.Tests.csproj
