name: CI
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
env:
  DOTNET_VERSION: '6.0.100-rc.2'
  
jobs:
  build-and-test:
    name: build-and-test-${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
#         os: [ubuntu-latest, windows-latest, macOS-latest]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
#       - uses: actions/setup-dotnet@v1
#         with:
#           dotnet-version: '6.0.100-rc.2'
#           include-prerelease: true
      - name: install dotnet 
        run: |
          wget  https://download.visualstudio.microsoft.com/download/pr/20283373-1d83-4879-8278-0afb7fd4035e/56f204f174743b29a656499ad0fc93c3/dotnet-sdk-6.0.100-rc.2.21505.57-linux-x64.tar.gz
          DOTNET_FILE=dotnet-sdk-6.0.100-rc.2.21505.57-linux-x64.tar.gz
          export DOTNET_ROOT=$(pwd)/dotnet
          echo $DOTNET_ROOT
          mkdir -p "$DOTNET_ROOT" && tar zxf "$DOTNET_FILE" -C "$DOTNET_ROOT"
          export PATH=$PATH:$DOTNET_ROOT
          dotnet version 
#       - uses: actions/checkout@v2
#       - name: Setup .NET Core
#         uses: actions/setup-dotnet@v1
#         with:
#           dotnet-version: ${{ env.DOTNET_VERSION }}

#       - name: Install dependencies
#         run: dotnet restore
      
#       - name: Test
#         run: dotnet test test/MASA.BuildingBlocks.DDD.Domain.Tests/MASA.BuildingBlocks.DDD.Domain.Tests.csproj
